---

- name: install apt package
  apt:
    name:  "{{ item }}"
    install_recommends: false
    update_cache:       true
    cache_valid_time:   3600
  with_items:
    - supervisor

- name: create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /etc/supervisor/conf.d
    - /var/log/supervisord

- name: config
  template:
    src: "{{ item }}.j2"
    dest: "/etc/supervisor/{{ item }}"
  with_items:
    - supervisord.conf
    - conf.d/programs.conf
  notify:
    - restart supervisor

- name: service start
  service:
    name:  "{{ item }}"
    state: started
  with_items:
    - supervisor