---

- name: install apt packages
  apt:
    name:  "{{ item }}"
    state: present
    install_recommends: false
    update_cache:       yes
    cache_valid_time:   300
  with_items:
    - curl
    - wget
    - htop

- name: install pip packages
  pip:
    name: httpie