---

- include: pip.yml

- name: install apt packages
  apt:
    name:  "{{ item }}"
    state: present
    install_recommends: false
    update_cache:       yes
    cache_valid_time:   300
  with_items: "{{ init_apt_packages }}"

- name: install pip packages
  pip:
    name: "{{ item }}"
  with_items: "{{ init_pip_packages }}"