---

# Basics
admin_user: ops
admin_user_group: admin

# vault_* vars are located in vault.yml encrypted file
# blackfire.io keys
php_blackfire_server_id: "{{ vault_blackfire_server_id }}"
php_blackfire_server_token: "{{ vault_blackfire_server_token }}"

# newrelic keys
newrelic_sysmond_key: "{{ vault_newrelic_sysmond_key }}"
newrelic_license: "{{ vault_newrelic_key }}"

# enable newrelic support for docker
docker_newrelic_support_enabled: true

# firewall rules
ufw_rules:
  - { port: 22, rule: allow }
  - { port: 80, rule: allow }
  - { port: 443, rule: allow }

# fail2ban custom jails
fail2ban_jails:
  DEFAULT:
    ignoreip: 127.0.0.1/8
    ignorecommand:
    bantime : 600
    findtime: 600
    maxretry: 3
    backend: auto
    usedns: warn
    destemail: root@localhost
    sendername: Fail2Ban
    sender:     fail2ban@localhost
    banaction:  iptables-multiport
    mta:        sendmail
    protocol:   tcp
    chain:      INPUT
    action_:    |
                %(banaction)s[name=%(__name__)s, port="%(port)s", protocol="%(protocol)s", chain="%(chain)s"]
    action_mw:  |
                %(banaction)s[name=%(__name__)s, port="%(port)s", protocol="%(protocol)s", chain="%(chain)s"]
                %(mta)s-whois[name=%(__name__)s, dest="%(destemail)s", protocol="%(protocol)s", chain="%(chain)s", sendername="%(sendername)s"]
    action_mwl: |
                %(banaction)s[name=%(__name__)s, port="%(port)s", protocol="%(protocol)s", chain="%(chain)s"]
                %(mta)s-whois-lines[name=%(__name__)s, dest="%(destemail)s", logpath=%(logpath)s, chain="%(chain)s", sendername="%(sendername)s"]
    action:     |
                %(action_)s
  ssh:
    enabled:    true
    port:       ssh
    filter:     sshd
    logpath:    /var/log/auth.log
    maxretry:   6

# list supervisor programs & events
supervisor_programs:
  mailhog:
    command: /usr/local/bin/mailhog -api-bind-addr :8025 -ui-bind-addr :8025
    autostart: "true"
    autorestart: "true"
    stderr_logfile: "{{ supervisor_log_path }}/mailhog-stderr.log"

supervisor_events:
  httpok:
    command: httpok -p mailhog http://localhost:8025
    events: TICK_60
