---

# Configure nginx vhosts
nginx_custom_vhosts:
  - port: "{{ nginx_port }}"
    server_name: "{{ ansible_host }}"
    root: "{{ nginx_default_root }}"
    access_log: /var/log/nginx/default.access.log
    error_log: /var/log/nginx/default.error.log
    active_php: true
    front_controller: index
    index: index.php
    strip_prefix: false
    rewrites: false
  - port: "{{ nginx_port }}"
    server_name: sulu.local
    root: /srv/www/sulu/web
    access_log: /var/log/nginx/sulu.local.access.log
    error_log: /var/log/nginx/sulu.local.error.log
    strip_prefix: app\.php
    active_php: true
    front_controller: website|admin|app|app_dev|config
    index: false
    rewrites:
      - name: admin
        location: /admin
        index: admin.php
      - name: website
        location: /
        index: website.php

# /etc/hosts custom configuration
custom_hosts:
  - sulu.local
