galaxy_info:
  author: Jérémy Baumgarth
  description: Install and configure blackfire APM for php
  company: Amiral Web
  license: MIT
  min_ansible_version: 2.1
  github_branch: master
  platforms:
    - name: Ubuntu
      versions:
      - trusty
      - wily
      - xenial
    - name: Debian
      versions:
      - jessie
  galaxy_tags:
    - blackfire
    - php
    - APM
    - lamp
    - lemp
dependencies: []
