---

- name: install apt packages
  apt:
    name:  "{{ item }}"
    state: present
    install_recommends: false
    update_cache:       true
  with_items:
    - memcached

- name: service start
  service:
    name:  "{{ item }}"
    state: started
  with_items:
    - memcached