---

- name: install apt packages
  apt:
    name:  "{{ item }}"
    state:              latest
    install_recommends: false
    update_cache:       yes
    cache_valid_time:   300
  with_items: "{{ php_packages }}"

- name: config
  template:
    src: "{{ item }}.j2"
    dest: "/etc/php5/fpm/{{ item }}"
  with_items:
    - php.ini
    - php-fpm.conf
    - opcache.blacklist
    - pool.d/pools.conf
  notify:
    - restart php-fpm

- name: config CLI
  template:
    src: "{{ item }}.j2"
    dest: "/etc/php5/cli/{{ item }}"
  with_items:
    - php.ini

- name: modules config
  template:
    src: "{{ item }}.j2"
    dest: "/etc/php5/mods-available/{{ item }}"
  with_items:
    - custom.ini
  notify:
    - restart php-fpm

- name: enable modules
  shell: "/usr/sbin/php5enmod {{ item }}"
  with_items:
    - newrelic
    - custom
  notify:
    - restart php-fpm

- name: service start
  service:
    name:  "{{ item }}"
    state: started
  with_items:
    - php5-fpm
