---

- name: add key
  apt_key:
    url: "{{ blackfire_key_url }}"
    state: present

- name: add repo
  apt_repository:
    repo: 'deb {{ blackfire_package_url }} any main'
    state: present
    update_cache: yes

- name: install apt packages
  apt:
    name: "{{ item }}"
    state:              latest
    install_recommends: false
    update_cache:       yes
    cache_valid_time:   300
  with_items:
    - blackfire-agent
    - blackfire-php
  notify:
    - restart blackfire-agent
    - restart php-fpm for blackfire

- name: config
  template:
    src: "{{ item }}.j2"
    dest: "{{ blackfire_directory }}/{{ item }}"
  with_items:
    - agent
  notify:
    - restart blackfire-agent
    - restart php-fpm for blackfire

- name: service start
  service:
    name: "{{ item }}"
    state: started
  with_items:
    - blackfire-agent
