---

# list supervisor programs
supervisor_programs:
  mailhog:
    command: /usr/local/bin/mailhog -api-bind-addr :8025 -ui-bind-addr :8025
    autostart: "true"
    autorestart: "true"
    stderr_logfile: "{{ supervisor_log_path }}/mailhog-stderr.log"

# Custom php config
php_ini_custom:
  Session:
    session.save_handler: memcached
    session.save_path: "{{ memcache_port }}:{{ memcache_listen_address }}"
  mail function:
    sendmail_from: me@example.com
    sendmail_path: "{{ mailhog_mhsendmail_path }}"
