---

# Pip configuration
pip_download_url: https://bootstrap.pypa.io/get-pip.py
pip_download_dest: /tmp
pip_version: latest
python: python
pip: pip

# Default apt packages to install
init_apt_packages:
  - vim
  - curl
  - wget
  - htop

# Default pip packages to install
init_pip_packages:
  - httpie
