---

- name: check install directory
  file:
    path: "{{ mailhog_install_dir }}"
    state: directory

- name: download MailHog and mhsendmail binaries
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0755
  with_items:
    - url: "{{ mailhog_binary_url }}"
      dest: "{{ mailhog_install_dir }}/mailhog"
    - url: "{{ mhsendmail_binary_url }}"
      dest: "{{ mailhog_install_dir }}/mhsendmail"

- name: replace sendmail by mhsendmail link
  file:
    src: "{{ mailhog_install_dir }}/mhsendmail"
    dest: "{{ sendmail_bin_path }}"
    state: link
