---

- name: haproxy restart
  command: "haproxy -c -f {{ haproxy_config_file }}"
  changed_when: true
  notify:
    - do haproxy restart

- name: do haproxy restart
  service:
    name:  haproxy
    state: restarted