---

# Include Base playbook for common tasks
- include: base.yml

# Specific playbook for monitoring servers
- hosts: monitoringservers
  become: true
  become_method: sudo
  roles:
    - { role: mailhog }
    - { role: _fluentd, tags: ['fluentd'] }
    - { role: _java, tags: ['java'] }
    - { role: _elasticsearch, tags: ['elasticsearch'] }
#    - { role: _statsd }
#    - { role: _graphite }
#    - { role: _grafana }
#    - { role: _kibana }
    - { role: supervisor }
