---

# list supervisor programs & events
supervisor_programs:
  mailhog:
    command: /usr/local/bin/mailhog -api-bind-addr :8025 -ui-bind-addr :8025
    autostart: "true"
    autorestart: "true"
    stderr_logfile: "{{ supervisor_log_path }}/mailhog-stderr.log"

supervisor_events:
  httpok:
    command: httpok -p mailhog http://localhost:8025
    events: TICK_60

# firewall rules
ufw_rules:
  - { port: 22, rule: allow }
  - { port: 80, rule: allow }
  - { port: 443, rule: allow }
  - { port: 8025, rule: allow }
  - { port: 9988, rule: allow }
  - { port: 9201, rule: allow }
  - { port: 9301, rule: allow }
  - { port: 5601, rule: allow }
  - { port: 24224, rule: allow }

# fluentd configuration
fluentd_plugins:
  - fluent-plugin-elasticsearch

fluentd_system_config:
  process_name: fluentd-central

fluentd_source_config:
  - "@type": forward
    port: 24224

fluentd_match_config:
  - pattern: "nginx.access"
    "@type": elasticsearch
    host: localhost
    port: 9201
    type_name: nginx_access
    logstash_format: "true"
    logstash_prefix: nginx_access

fluentd_filter_config: []
